Repository Cihaan/versioning-project, pull requests merged in 2022-11, with the labels that each got.

#23 feat(html): html of the index
  index.html
Labels: feat

#29 chore: create .gitignore
  .gitignore
Labels: chore

#45 Fix css js
  README.md
  assets/preview.png
  css/animate.css
  css/animate.min.css
  css/bootstrap.min.css
  css/font-awesome.min.css
  css/index.css
  css/main.css
  css/owl.carousel.css
  css/responsive.css
  index.html
  js/bootstrap.min.js
  js/jquery.nav.js
  js/jquery.sticky.js
  js/main.js
  js/min/main.min.js
  js/plugins.js
  js/vendor/jquery-1.10.2.min.js
  js/vendor/modernizr-2.6.2.min.js
  js/wow.min.js
Labels: docs, feat, deploy
